//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hms2.Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string qualification { get; set; }
        public string age { get; set; }
        public string Cellnum { get; set; }
        public string CNIC { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
    }
}
